sqeleton vendoring PoC
datafold/data-diff pull request #480
Opened 2023-04-05 14:39 UTC by vvkh

Basically
```
mkdir vendor
cd vendor
git clone git@github.com:datafold/sqeleton.git
rm -rf sqeletion/.git
rm -rf sqeleton/.github
```
+ updates in the pyproject.toml file

2023-04-05 14:58 UTC, erezsh commented
What is the point of this change?

2023-04-05 19:13 UTC, vvkh commented
@erezsh we briefly discussed the idea with @wvanbergen with the primary goal of improving time to market and simplifying the release process. For now, it's a PoC to check if such setup works without heavy refactoring, so you can ignore the PR.

2023-04-05 19:13 UTC, vvkh commented
- [ ] no merge

2023-04-05 19:19 UTC, wvanbergen commented
Because we shelved our plans for the other tool that would use the sqeleton library, it doesn't really make much sense to have it in a separate repository anymore. It makes contributing to datadiff harder than it has to be, and makes releases a more complicated process. So we decided to merge these repositories back into a single codebase.

2023-04-06 07:06 UTC, nolar requested changes
Thank you for taking care of it. Luckily, we have no rush on this merging, so I suggest that we take a different route — the one that preserves the git history of changes and embeds sqeleton as one extra top-level package into the library — instead of bringing it as a vendored subdirectory which requires import-path injections.

Essentially, that is `git remote add sqeleton …` + `git merge sqeleton/master  --allow-unrelated-histories`, and then resolve the conflicts on the same-named files (mostly CI & metadata). I am already working on it.

2023-04-06 07:13 UTC, nolar commented on pyproject.toml
> +sqeleton = { path = "./vendor/sqeleton", develop = true }
On a side note: I wonder, will this approach also package the files properly into tarballs & wheels and install it in a clean environment that is not git-based (i.e. `pip install data-diff`)?

2023-04-06 07:54 UTC, nolar commented
Here is an alternative proposal with the git history preserved: https://github.com/datafold/data-diff/pull/485

2023-04-13 16:29 UTC, williebsweet commented
@nolar @wvanbergen  Should we close this?

2023-04-14 07:53 UTC, closed without merging