Support missing dbt connection attributes aliases
datafold/data-diff pull request #690
Opened 2023-08-25 13:38 UTC by sar009

Supporting missing dbt connection attribute aliases. 

- [BigQuery](https://github.com/dbt-labs/dbt-bigquery/blob/d7fb235a42780841c82ea5b01a647b3416070afe/dbt/adapters/bigquery/connections.py#L150)
- [Redshift](https://github.com/dbt-labs/dbt-redshift/blob/e5bfa3bc433f658daa23f669bf58c4dbbea9ab64/dbt/adapters/redshift/connections.py#L139)
- [Databricks](https://github.com/databricks/dbt-databricks/blob/5c7e68536b7164b0d8c91a629945c6d1d92c0d88/dbt/adapters/databricks/connections.py#L119)
- [Postgres](https://github.com/dbt-labs/dbt-core/blob/1afbb87e99f8a45202658ae8fcdad971928a248f/plugins/postgres/dbt/adapters/postgres/connections.py#L37)

2023-08-31 16:30 UTC, sungchun12 requested changes
Can you add tests where these new attributes get called in the respective `profiles.yml` and work as expected? 

@sar009

2023-09-25 17:00 UTC, dlawin approved these changes

2023-09-25 17:01 UTC, dlawin approved these changes

2023-09-25 17:02 UTC, dlawin commented
> Can you add tests where these new attributes get called in the respective `profiles.yml` and work as expected?
> 
> @sar009

I think we can go ahead and merge it

2023-10-09 18:23 UTC, sungchun12 approved these changes

2023-10-09 18:24 UTC, sungchun12 commented
I don't see regression risks here anymore.

2023-10-09 18:24 UTC, merged