Namespacing CLI options
datafold/data-diff pull request #860
Opened 2024-01-25 12:49 UTC by sar009

2024-01-25 18:21 UTC, sar009 commented
fixing https://github.com/datafold/data-diff/issues/859

2024-01-25 18:38 UTC, sungchun12 commented
Can you add a fuller description on your approach in this PR? I'll plan to review this next week when it's ready!

2024-01-25 19:14 UTC, sar009 commented
@sungchun12 I have updated the description please have a look.

2024-02-05 20:32 UTC, sungchun12 requested changes
Overall, I really like this approach and you did a great job of cleaning up the implementation emails and reducing `kwargs` bloat for function calls.

Once you update the data class for a pydantic class and update the relevant attribute calls, I'll give this another review and aim to merge this week!

2024-02-05 20:32 UTC, sungchun12 commented on data_diff/__init__.py
> +    key_columns: Tuple[str] = ("id",),
thanks, good catch. You're reminding me that we need to add static type checking to this codebase

2024-02-05 20:32 UTC, sungchun12 commented on data_diff/config.py
>                  raise ValueError(f"Specified database1 but not {attr}. Must specify all 4 arguments, or neither.")
```suggestion
                raise ValueError(f"Specified database1 but not {attr}. Must specify all 4 arguments (database1, table1, database2, table2), or none.")
```

Make it clear what 4 arguments are needed

2024-02-05 20:32 UTC, sungchun12 commented on data_diff/cli_options.py
> +class CliOptions:
Seeing all this really puts into perspective just how many CLI options are available that need validation. Can you refactor this using pydantic? 

Until we have static type checking in place, runtime type validation will serve this better

quick pseudo-code
```python
from typing import Optional, Literal, Dict, Union, Tuple
from pydantic import BaseModel


class CliOptions(BaseModel):
    bisection_factor: int
    bisection_threshold: int
    table_write_limit: int
    database1: Union[str, Dict, None] = None
    table1: Optional[str] = None
    database2: Union[str, Dict, None] = None
    table2: Optional[str] = None
    key_columns: Tuple[str, ...] = ()
    update_column: Optional[str] = None
    columns: Tuple[str, ...] = ()
    limit: Optional[int] = None
    materialize_to_table: Optional[str] = None
    min_age: Optional[str] = None
    max_age: Optional[str] = None
    stats: bool = False
    debug: bool = False
    json_output: bool = False
    verbose: bool = False
    version: bool = False
    interactive: bool = False
    no_tracking: bool = False
    case_sensitive: bool = False
    assume_unique_key: bool = False
    sample_exclusive_rows: bool = False
    materialize_all_rows: bool = False
    threads: Union[None, int, Literal["serial"]] = None
    threads1: Optional[int] = None
    threads2: Optional[int] = None
    threaded: bool = False
    where: Optional[str] = None
    algorithm: Literal["auto", "joindiff", "hashdiff"] = "auto"
    conf: Optional[str] = None
    run: Optional[str] = None
    dbt: bool = False
    cloud: bool = False
    dbt_profiles_dir: Optional[str] = None
    dbt_project_dir: Optional[str] = None
    select: Optional[str] = None
    state: Optional[str] = None
    prod_database: Optional[str] = None
    prod_schema: Optional[str] = None
    __conf__: Optional[Dict] = None
```

2024-02-05 20:32 UTC, sungchun12 commented on data_diff/cli_options.py
> +class CliOptions:
You will have to change the attribute calls for the rest of the files as a result

2024-02-05 20:32 UTC, sungchun12 commented on tests/test_main.py
> +        assert str(value_error.exception) == "Error: threads must be of type int, or value must be 'serial'."
pydantic will resolve this at runtime validation, but this custom error message is nice

2024-02-20 10:04 UTC, sar009 commented
@sungchun12 I have addressed the review comments please take a look

2024-02-26 23:02 UTC, sungchun12 commented on data_diff/__main__.py
> +    type=str,
why is this a string?

2024-02-26 23:12 UTC, sungchun12 commented
Mirror this PR for the full test suite to uncover any edge cases: https://github.com/datafold/data-diff/pull/871

2024-02-27 17:50 UTC, sungchun12 requested changes
Overall, really good!

Just need new tests for these methods/functions given this codebase hasn't tested them before and we need to make sure the new args we're passing are doing exactly as expected.

- `_apply_config`
- `apply_config_from_file`
- `_print_result`
- `_data_diff`
- `create_schema`
- `diff_schemas`

2024-02-27 17:50 UTC, sungchun12 commented on data_diff/cli_options.py
> +class CliOptions(BaseModel):
This class is bloated and will become bloated over time, but I'm willing to accept that tradeoff for better runtime validation of flag types and simplification of `kwargs**` across method calls. Overall, this PR has opened my eyes that a major refactor needs to happen across lots of the codebase for simpler data flows, but in the short-term, this approach is worth it.

2024-03-11 06:22 UTC, sar009 commented on data_diff/__main__.py
>      default=None,
https://github.com/datafold/data-diff/pull/860/files#diff-c4d05fd628acd83c42409afcbd38e6fca96261992bea7d774dd5d7ab598716a2R498

threads can be `serial`

2024-05-17 06:33 UTC, closed without merging